import React, {useContext, useState, useEffect} from 'react'

const customerData = JSON.stringify(
  [{
    "id": "brownnr289te",
    "name": "Brown",
    "prefix": "Dr",
    "addressLine1": "The Meadow",
    "addressLine2": "Mundesley Road",
    "town": "Paston",
    "county": "Norfolk",
    "postcode": "NR28 9TE",
    "mobile": "07462 982497",
    "home": "01510 538014",
    "email": "brown7462@gmail.com",
    "frequency": 15,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "hallnr280dd",
    "name": "Hall",
    "prefix": "Mr",
    "addressLine1": "102 Mundesley Road",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0DD",
    "mobile": "07598 999445",
    "home": "01225 822205",
    "email": "hall3358@gmail.com",
    "frequency": 20,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "palmernr116st",
    "name": "Palmer",
    "prefix": "Miss",
    "addressLine1": "7 Mash's Row",
    "addressLine2": null,
    "town": "Aylsham",
    "county": "Norfolk",
    "postcode": "NR11 6ST",
    "mobile": "07032 297971",
    "home": "01774 685966",
    "email": "palmer0525@gmail.com",
    "frequency": 11,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "greennr118pt",
    "name": "Green",
    "prefix": "Ms",
    "addressLine1": "Park Wall Farm",
    "addressLine2": null,
    "town": "Aylmerton",
    "county": "Norfolk",
    "postcode": "NR11 8PT",
    "mobile": "07991 961091",
    "home": "01708 202174",
    "email": "green6734@gmail.com",
    "frequency": 19,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "clarknr289te",
    "name": "Clark",
    "prefix": "Mr",
    "addressLine1": "Poppyland",
    "addressLine2": "Mundesley Road",
    "town": "Paston",
    "county": "Norfolk",
    "postcode": "NR28 9TE",
    "mobile": "07117 726055",
    "home": "01046 085610",
    "email": "clark2221@gmail.com",
    "frequency": 18,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "quinnnr118pt",
    "name": "Quinn",
    "prefix": "Mr",
    "addressLine1": "Spring Cottage",
    "addressLine2": "Park Road",
    "town": "Aylmerton",
    "county": "Norfolk",
    "postcode": "NR11 8PT",
    "mobile": "07707 219116",
    "home": "01312 681325",
    "email": "quinn4390@gmail.com",
    "frequency": 21,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "harpernr118jp",
    "name": "Harper",
    "prefix": "Lady",
    "addressLine1": "14a Heath Lane",
    "addressLine2": null,
    "town": "Mundesley",
    "county": "Norfolk",
    "postcode": "NR11 8JP",
    "mobile": "07377 592760",
    "home": "01094 425295",
    "email": "harper4329@gmail.com",
    "frequency": 14,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "johnsonnr280qu",
    "name": "Johnson",
    "prefix": "Ms",
    "addressLine1": "30 Kingsleigh Close",
    "addressLine2": null,
    "town": "Trunch",
    "county": "Norfolk",
    "postcode": "NR28 0QU",
    "mobile": "07630 944206",
    "home": "01570 194981",
    "email": "johnson1227@gmail.com",
    "frequency": 20,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "owennr280hy",
    "name": "Owen",
    "prefix": "Mr",
    "addressLine1": "15 Morrison Close",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0HY",
    "mobile": "07373 932086",
    "home": "01298 858767",
    "email": "owen2085@gmail.com",
    "frequency": 11,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "rossnr116st",
    "name": "Ross",
    "prefix": "Mr",
    "addressLine1": "1 Mash's Row",
    "addressLine2": null,
    "town": "Aylsham",
    "county": "Norfolk",
    "postcode": "NR11 6ST",
    "mobile": "07809 993893",
    "home": "01134 217640",
    "email": "ross6502@gmail.com",
    "frequency": 7,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "carrnr289ya",
    "name": "Carr",
    "prefix": "Mr",
    "addressLine1": "36 Long Barrow Drive",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9YA",
    "mobile": "07738 667933",
    "home": "01874 151430",
    "email": "carr5460@gmail.com",
    "frequency": 16,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "allennr280hz",
    "name": "Allen",
    "prefix": "Dr",
    "addressLine1": "23 Simpson Close",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0HZ",
    "mobile": "07996 541150",
    "home": "01867 614516",
    "email": "allen8386@gmail.com",
    "frequency": 12,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "hunternr279hg",
    "name": "Hunter",
    "prefix": "Dr",
    "addressLine1": "7 High Street",
    "addressLine2": null,
    "town": "Cromer",
    "county": "Norfolk",
    "postcode": "NR27 9HG",
    "mobile": "07294 095792",
    "home": "01023 282286",
    "email": "hunter3445@gmail.com",
    "frequency": 11,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "wilsonnr270ab",
    "name": "Wilson",
    "prefix": "Lady",
    "addressLine1": "Cliffside House",
    "addressLine2": "12 High Street",
    "town": "Overstrand",
    "county": "Norfolk",
    "postcode": "NR27 0AB",
    "mobile": "07383 204253",
    "home": "01305 402772",
    "email": "wilson7704@gmail.com",
    "frequency": 7,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "davisnr118as",
    "name": "Davis",
    "prefix": "Mx",
    "addressLine1": "9 Hawthorn Rise",
    "addressLine2": null,
    "town": "Mundesley",
    "county": "Norfolk",
    "postcode": "NR11 8AS",
    "mobile": "07956 359300",
    "home": "01041 894347",
    "email": "davis8545@gmail.com",
    "frequency": 11,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "rogersnr289te",
    "name": "Rogers",
    "prefix": "Miss",
    "addressLine1": "Jenbar Villa's",
    "addressLine2": "Mundesley Road",
    "town": "Paston",
    "county": "Norfolk",
    "postcode": "NR28 9TE",
    "mobile": "07174 371398",
    "home": "01650 468435",
    "email": "rogers9445@gmail.com",
    "frequency": 10,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "andersonnr116st",
    "name": "Anderson",
    "prefix": "Lady",
    "addressLine1": "5 Mash's Row",
    "addressLine2": null,
    "town": "Aylsham",
    "county": "Norfolk",
    "postcode": "NR11 6ST",
    "mobile": "07355 945980",
    "home": "01769 575111",
    "email": "anderson3409@gmail.com",
    "frequency": 11,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "jenningsnr280un",
    "name": "Jennings",
    "prefix": "Mr",
    "addressLine1": "Firstport Retirement Property Services",
    "addressLine2": "Angel Court",
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0UN",
    "mobile": "07845 642444",
    "home": "01544 918566",
    "email": "jennings3874@gmail.com",
    "frequency": 14,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "daynr280rq",
    "name": "Day",
    "prefix": "Mx",
    "addressLine1": "The Staithe",
    "addressLine2": "Swafield",
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0RQ",
    "mobile": "07684 889957",
    "home": "01206 924025",
    "email": "day3328@gmail.com",
    "frequency": 15,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "jacksonnr289ya",
    "name": "Jackson",
    "prefix": "Miss",
    "addressLine1": "5 Long Barrow Drive",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9YA",
    "mobile": "07332 653475",
    "home": "01726 393558",
    "email": "jackson8904@gmail.com",
    "frequency": 21,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "hewittnr280hy",
    "name": "Hewitt",
    "prefix": "Dr",
    "addressLine1": "14 Morrison Close",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0HY",
    "mobile": "07399 597424",
    "home": "01215 238409",
    "email": "hewitt3734@gmail.com",
    "frequency": 19,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "morgannr118lr",
    "name": "Morgan",
    "prefix": "Mr",
    "addressLine1": "13 Cantab",
    "addressLine2": "Beckmeadow Way",
    "town": "Mundesley",
    "county": "Norfolk",
    "postcode": "NR11 8LR",
    "mobile": "07265 155986",
    "home": "01359 334571",
    "email": "morgan4951@gmail.com",
    "frequency": 21,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "kellynr280dq",
    "name": "Kelly",
    "prefix": "Ms",
    "addressLine1": "10 Mayfield Way",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0DQ",
    "mobile": "07158 973496",
    "home": "01478 823907",
    "email": "kelly5600@gmail.com",
    "frequency": 9,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "rowenr129nj",
    "name": "Rowe",
    "prefix": "Mr",
    "addressLine1": "Herbal",
    "addressLine2": "Union Road",
    "town": "Smallburgh",
    "county": "Norfolk",
    "postcode": "NR12 9NJ",
    "mobile": "07580 946639",
    "home": "01633 194082",
    "email": "rowe7122@gmail.com",
    "frequency": 9,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "reynoldsnr270ab",
    "name": "Reynolds",
    "prefix": "Mrs",
    "addressLine1": "12 High Street",
    "addressLine2": null,
    "town": "Overstrand",
    "county": "Norfolk",
    "postcode": "NR27 0AB",
    "mobile": "07764 706679",
    "home": "01123 934612",
    "email": "reynolds4932@gmail.com",
    "frequency": 17,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "austinnr289bj",
    "name": "Austin",
    "prefix": "Mr",
    "addressLine1": "Firstport Retirement Property Services",
    "addressLine2": "Glaven Close",
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9BJ",
    "mobile": "07861 708224",
    "home": "01576 663858",
    "email": "austin7066@gmail.com",
    "frequency": 7,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "hardingnr120pe",
    "name": "Harding",
    "prefix": "Mr",
    "addressLine1": "Lighthousehouse Inn",
    "addressLine2": "Coast Road",
    "town": "Walcott",
    "county": "Norfolk",
    "postcode": "NR12 0PE",
    "mobile": "07675 271840",
    "home": "01479 454080",
    "email": "harding6538@gmail.com",
    "frequency": 13,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "hammondnr289ya",
    "name": "Hammond",
    "prefix": "Mr",
    "addressLine1": "7 Long Barrow Drive",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9YA",
    "mobile": "07186 972720",
    "home": "01096 617660",
    "email": "hammond4015@gmail.com",
    "frequency": 18,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "buckleynr289ya",
    "name": "Buckley",
    "prefix": "Mr",
    "addressLine1": "3 Long Barrow Drive",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9YA",
    "mobile": "07600 867889",
    "home": "01659 507972",
    "email": "buckley6814@gmail.com",
    "frequency": 10,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "burgessnr120ey",
    "name": "Burgess",
    "prefix": "Mr",
    "addressLine1": "Bacton Holiday Properties",
    "addressLine2": "Pilgrims House",
    "town": "Bacton",
    "county": "Norfolk",
    "postcode": "NR12 0EY",
    "mobile": "07814 304010",
    "home": "01547 386671",
    "email": "burgess9311@gmail.com",
    "frequency": 10,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "glovernr289jq",
    "name": "Glover",
    "prefix": "Mrs",
    "addressLine1": "8 Youngmans Close",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9JQ",
    "mobile": "07274 229064",
    "home": "01824 070663",
    "email": "glover9685@gmail.com",
    "frequency": 19,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "rileynr289ya",
    "name": "Riley",
    "prefix": "Mr",
    "addressLine1": "63 Long Barrow Drive",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9YA",
    "mobile": "07540 924519",
    "home": "01046 626915",
    "email": "riley4246@gmail.com",
    "frequency": 16,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "willisnr289sg",
    "name": "Willis",
    "prefix": "Dr",
    "addressLine1": "13 St Andrews Close",
    "addressLine2": null,
    "town": "Wostead",
    "county": "Norfolk",
    "postcode": "NR28 9SG",
    "mobile": "07270 820107",
    "home": "01353 154822",
    "email": "willis5592@gmail.com",
    "frequency": 16,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "richardsonnr280dg",
    "name": "Richardson",
    "prefix": "Lady",
    "addressLine1": "28 Swafield Rise",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0DG",
    "mobile": "07886 611949",
    "home": "01643 530620",
    "email": "richardson4699@gmail.com",
    "frequency": 20,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "hawkinsnr289jq",
    "name": "Hawkins",
    "prefix": "Dr",
    "addressLine1": "2 Mill Road",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9JQ",
    "mobile": "07214 067706",
    "home": "01078 626986",
    "email": "hawkins1305@gmail.com",
    "frequency": 8,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "doylenr33pl",
    "name": "Doyle",
    "prefix": "Mr",
    "addressLine1": "20 Peel Mews",
    "addressLine2": "Anchor Quay",
    "town": "Norwich",
    "county": "Norfolk",
    "postcode": "NR3 3PL",
    "mobile": "07035 120275",
    "home": "01774 141320",
    "email": "doyle4490@gmail.com",
    "frequency": 19,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "wellsnr289ya",
    "name": "Wells",
    "prefix": "Mr",
    "addressLine1": "20 Long Barrow Drive",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9YA",
    "mobile": "07159 135109",
    "home": "01741 033729",
    "email": "wells7731@gmail.com",
    "frequency": 10,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "perrynr120hb",
    "name": "Perry",
    "prefix": "Mr",
    "addressLine1": "3 Coastguard cottages",
    "addressLine2": "Walcott Road",
    "town": "Bacton",
    "county": "Norfolk",
    "postcode": "NR12 0HB",
    "mobile": "07344 895471",
    "home": "01394 336805",
    "email": "perry6163@gmail.com",
    "frequency": 14,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "heathnr280hw",
    "name": "Heath",
    "prefix": "Lord",
    "addressLine1": "23 Greens Road",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0HW",
    "mobile": "07877 017345",
    "home": "01155 904937",
    "email": "heath3897@gmail.com",
    "frequency": 14,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "batesnr116st",
    "name": "Bates",
    "prefix": "Mr",
    "addressLine1": "2 Mash's Row",
    "addressLine2": null,
    "town": "Aylsham",
    "county": "Norfolk",
    "postcode": "NR11 6ST",
    "mobile": "07152 581308",
    "home": "01420 959977",
    "email": "bates0773@gmail.com",
    "frequency": 21,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "steelenr129nj",
    "name": "Steele",
    "prefix": "Dr",
    "addressLine1": "Just Us",
    "addressLine2": "Union Road",
    "town": "Smallborough",
    "county": "Norfolk",
    "postcode": "NR12 9NJ",
    "mobile": "07657 532154",
    "home": "01831 314718",
    "email": "steele5451@gmail.com",
    "frequency": 16,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "johnstonnr280dg",
    "name": "Johnston",
    "prefix": "Lady",
    "addressLine1": "45 Swafield Rise",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0DG",
    "mobile": "07235 769134",
    "home": "01096 733765",
    "email": "johnston8591@gmail.com",
    "frequency": 21,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "hollandnr128se",
    "name": "Holland",
    "prefix": "Mr",
    "addressLine1": "14 Orchard Estate",
    "addressLine2": "Market Street",
    "town": "Tunstead",
    "county": "Norfolk",
    "postcode": "NR12 8SE",
    "mobile": "07676 202200",
    "home": "01580 464649",
    "email": "holland6100@gmail.com",
    "frequency": 18,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "barnettnr280sz",
    "name": "Barnett",
    "prefix": "Mrs",
    "addressLine1": "8 Gooch Close",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0SZ",
    "mobile": "07839 304336",
    "home": "01596 239263",
    "email": "barnett0515@gmail.com",
    "frequency": 13,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "jonesnr289ya",
    "name": "Jones",
    "prefix": "Miss",
    "addressLine1": "42 Thirlby Road",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9YA",
    "mobile": "07967 609202",
    "home": "01149 706649",
    "email": "jones0630@gmail.com",
    "frequency": 11,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "spencernr270pz",
    "name": "Spencer",
    "prefix": "Mr",
    "addressLine1": "Swinton House",
    "addressLine2": "Old Coach Road",
    "town": "Cromer",
    "county": "Norfolk",
    "postcode": "NR27 0PZ",
    "mobile": "07634 033788",
    "home": "01201 977248",
    "email": "spencer2655@gmail.com",
    "frequency": 16,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "barrynr280lx",
    "name": "Barry",
    "prefix": "Mrs",
    "addressLine1": "1 Page Close",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0LX",
    "mobile": "07627 559790",
    "home": "01054 298107",
    "email": "barry2199@gmail.com",
    "frequency": 14,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "hayesnr280un",
    "name": "Hayes",
    "prefix": "Lord",
    "addressLine1": "30 Angel Court",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0UN",
    "mobile": "07405 969641",
    "home": "01630 077214",
    "email": "hayes9623@gmail.com",
    "frequency": 7,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "grantnr270nz",
    "name": "Grant",
    "prefix": "Dr",
    "addressLine1": "31 Bracken Avenue",
    "addressLine2": null,
    "town": "Overstrand",
    "county": "Norfolk",
    "postcode": "NR27 0NZ",
    "mobile": "07026 955772",
    "home": "01129 124030",
    "email": "grant5226@gmail.com",
    "frequency": 21,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "gardnernr270nz",
    "name": "Gardner",
    "prefix": "Lord",
    "addressLine1": "40 Bracken Avenue",
    "addressLine2": null,
    "town": "Overstrand",
    "county": "Norfolk",
    "postcode": "NR27 0NZ",
    "mobile": "07665 761069",
    "home": "01992 990369",
    "email": "gardner3032@gmail.com",
    "frequency": 18,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "goodwinnr118jz",
    "name": "Goodwin",
    "prefix": "Lady",
    "addressLine1": "29 Gorse Close",
    "addressLine2": null,
    "town": "Mundesley",
    "county": "Norfolk",
    "postcode": "NR11 8JZ",
    "mobile": "07600 092471",
    "home": "01772 311289",
    "email": "goodwin9700@gmail.com",
    "frequency": 10,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "coxnr280dq",
    "name": "Cox",
    "prefix": "Lord",
    "addressLine1": "6 Maybank",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0DQ",
    "mobile": "07142 355862",
    "home": "01948 487925",
    "email": "cox1444@gmail.com",
    "frequency": 19,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "chambersnr280fe",
    "name": "Chambers",
    "prefix": "Dr",
    "addressLine1": "Equator House",
    "addressLine2": "Cornish Way Business Park",
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0FE",
    "mobile": "07626 262049",
    "home": "01122 266005",
    "email": "chambers7237@gmail.com",
    "frequency": 20,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "barrettnr24sf",
    "name": "Barrett",
    "prefix": "Mr",
    "addressLine1": "1 Bank Plain",
    "addressLine2": null,
    "town": "Norwich",
    "county": "Norfolk",
    "postcode": "NR2 4SF",
    "mobile": "07701 282694",
    "home": "01429 407119",
    "email": "barrett2883@gmail.com",
    "frequency": 7,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "warrennr118jz",
    "name": "Warren",
    "prefix": "Lady",
    "addressLine1": "36 Gorse Close",
    "addressLine2": null,
    "town": "Mundesley",
    "county": "Norfolk",
    "postcode": "NR11 8JZ",
    "mobile": "07692 485672",
    "home": "01288 719964",
    "email": "warren1651@gmail.com",
    "frequency": 18,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "littlenr289bj",
    "name": "Little",
    "prefix": "Ms",
    "addressLine1": "9 Glaven Close",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9BJ",
    "mobile": "07906 124083",
    "home": "01214 720610",
    "email": "little0430@gmail.com",
    "frequency": 10,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "coatesnr120nx",
    "name": "Coates",
    "prefix": "Miss",
    "addressLine1": "Hayfield Cottage",
    "addressLine2": "2 The Green",
    "town": "Walcott Green",
    "county": "Norfolk",
    "postcode": "NR12 0NX",
    "mobile": "07137 644074",
    "home": "01544 461409",
    "email": "coates1262@gmail.com",
    "frequency": 13,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "archernr280ea",
    "name": "Archer",
    "prefix": "Dr",
    "addressLine1": "35 Buxton Villas",
    "addressLine2": "Station Road",
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "Nr28 0EA",
    "mobile": "07019 142778",
    "home": "01870 738083",
    "email": "archer3781@gmail.com",
    "frequency": 12,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "mannnr280pe",
    "name": "Mann",
    "prefix": "Mx",
    "addressLine1": "Glenelg",
    "addressLine2": "Trunch Road",
    "town": "Swafield",
    "county": "Norfolk",
    "postcode": "NR28 0PE",
    "mobile": "07043 969285",
    "home": "01452 597242",
    "email": "mann2930@gmail.com",
    "frequency": 12,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "howellnr289xr",
    "name": "Howell",
    "prefix": "Mr",
    "addressLine1": "91 Brick Kiln Road",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9XR",
    "mobile": "07752 930114",
    "home": "01217 847429",
    "email": "howell5933@gmail.com",
    "frequency": 12,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "dalenr289py",
    "name": "Dale",
    "prefix": "Dr",
    "addressLine1": "Orchard House",
    "addressLine2": "Yarmouth Road",
    "town": "Dilham",
    "county": "Norfolk",
    "postcode": "NR28 9PY",
    "mobile": "07018 858124",
    "home": "01286 449589",
    "email": "dale7497@gmail.com",
    "frequency": 21,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "olivernr280aj",
    "name": "Oliver",
    "prefix": "Mx",
    "addressLine1": "1 Folgate Road",
    "addressLine2": "Lyngate Industrial Estate",
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0AJ",
    "mobile": "07649 777908",
    "home": "01022 181367",
    "email": "oliver1578@gmail.com",
    "frequency": 15,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "wheelernr129df",
    "name": "Wheeler",
    "prefix": "Mr",
    "addressLine1": "Seaton House",
    "addressLine2": "Brunstead Road",
    "town": "Stalham",
    "county": "Norfolk",
    "postcode": "NR12 9DF",
    "mobile": "07974 586723",
    "home": "01162 077880",
    "email": "wheeler8686@gmail.com",
    "frequency": 20,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "andrewsnr280dq",
    "name": "Andrews",
    "prefix": "Lord",
    "addressLine1": "13 Mayfield Way",
    "addressLine2": "The Laurels",
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0DQ",
    "mobile": "07938 177828",
    "home": "01743 866706",
    "email": "andrews9866@gmail.com",
    "frequency": 12,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "watersnr280sd",
    "name": "Waters",
    "prefix": "Miss",
    "addressLine1": "16 Lawn Close",
    "addressLine2": null,
    "town": "Knapton",
    "county": "Norfolk",
    "postcode": "NR28 0SD",
    "mobile": "07192 962704",
    "home": "01970 964907",
    "email": "waters5115@gmail.com",
    "frequency": 17,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "mossnr289jb",
    "name": "Moss",
    "prefix": "Mr",
    "addressLine1": "32 Thirlby Road",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9JB",
    "mobile": "07587 316986",
    "home": "01642 174666",
    "email": "moss4184@gmail.com",
    "frequency": 20,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "briggsnr289ya",
    "name": "Briggs",
    "prefix": "Mr",
    "addressLine1": "6 Long Barrow Drive",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9YA",
    "mobile": "07082 914389",
    "home": "01155 329162",
    "email": "briggs0054@gmail.com",
    "frequency": 10,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "westnr279hz",
    "name": "West",
    "prefix": "Mr",
    "addressLine1": "Sutherland Court Gardens",
    "addressLine2": "13 West Street",
    "town": "Cromer",
    "county": "Norfolk",
    "postcode": "NR27 9HZ",
    "mobile": "07683 605677",
    "home": "01514 375652",
    "email": "west2219@gmail.com",
    "frequency": 20,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "blakenr270pz",
    "name": "Blake",
    "prefix": "Mr",
    "addressLine1": "1b Swinton House",
    "addressLine2": "Old Coach Road",
    "town": "Cromer",
    "county": "Norfolk",
    "postcode": "NR27 0PZ",
    "mobile": "07553 026616",
    "home": "01077 074248",
    "email": "blake1792@gmail.com",
    "frequency": 12,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "pattersonnr116dr",
    "name": "Patterson",
    "prefix": "Mr",
    "addressLine1": "25 Pound Lane",
    "addressLine2": null,
    "town": "Aylsham",
    "county": "Norfolk",
    "postcode": "NR11 6DR",
    "mobile": "07298 532782",
    "home": "01795 338812",
    "email": "patterson8788@gmail.com",
    "frequency": 13,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "higginsnr280dq",
    "name": "Higgins",
    "prefix": "Lady",
    "addressLine1": "14 Mayfield Way",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0DQ",
    "mobile": "07988 578204",
    "home": "01111 089413",
    "email": "higgins4345@gmail.com",
    "frequency": 21,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "francisnr289dq",
    "name": "Francis",
    "prefix": "Mr",
    "addressLine1": "Guyton House",
    "addressLine2": "5 Vicarage Street",
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9DQ",
    "mobile": "07908 962165",
    "home": "01283 662605",
    "email": "francis6422@gmail.com",
    "frequency": 11,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "barbernr289ba",
    "name": "Barber",
    "prefix": "Mx",
    "addressLine1": "15 Thirlby Road",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 9BA",
    "mobile": "07819 040527",
    "home": "01409 981977",
    "email": "barber1447@gmail.com",
    "frequency": 15,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "frostnr289th",
    "name": "Frost",
    "prefix": "Lord",
    "addressLine1": "8 Bears Road",
    "addressLine2": null,
    "town": "Paston",
    "county": "Norfolk",
    "postcode": "NR28 9TH",
    "mobile": "07774 056601",
    "home": "01075 970683",
    "email": "frost2954@gmail.com",
    "frequency": 17,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "griffinnr116dr",
    "name": "Griffin",
    "prefix": "Lady",
    "addressLine1": "23 Pound Lane",
    "addressLine2": null,
    "town": "Aylsham",
    "county": "Norfolk",
    "postcode": "NR11 6DR",
    "mobile": "07930 750244",
    "home": "01903 693232",
    "email": "griffin7327@gmail.com",
    "frequency": 11,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "middletonnr118bn",
    "name": "Middleton",
    "prefix": "Mr",
    "addressLine1": "6a Paston Road",
    "addressLine2": null,
    "town": "Mundesley",
    "county": "Norfolk",
    "postcode": "NR11 8BN",
    "mobile": "07867 453882",
    "home": "01937 199321",
    "email": "middleton3929@gmail.com",
    "frequency": 8,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "murphynr118jz",
    "name": "Murphy",
    "prefix": "Mr",
    "addressLine1": "13 Gorse Close",
    "addressLine2": null,
    "town": "Mundesley",
    "county": "Norfolk",
    "postcode": "NR11 8JZ",
    "mobile": "07373 288469",
    "home": "01087 008566",
    "email": "murphy4692@gmail.com",
    "frequency": 16,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "lambertnr118lp",
    "name": "Lambert",
    "prefix": "Lady",
    "addressLine1": "11 Beckmeadow Way",
    "addressLine2": null,
    "town": "Mundesley",
    "county": "Norfolk",
    "postcode": "NR11 8LP",
    "mobile": "07045 358274",
    "home": "01094 366753",
    "email": "lambert1404@gmail.com",
    "frequency": 13,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  },
  {
    "id": "kentnr280ut",
    "name": "Kent",
    "prefix": "Miss",
    "addressLine1": "14 Alder Close",
    "addressLine2": null,
    "town": "North Walsham",
    "county": "Norfolk",
    "postcode": "NR28 0UT",
    "mobile": "07189 764382",
    "home": "01008 682323",
    "email": "kent7267@gmail.com",
    "frequency": 20,
    "contractDetails": "Contact to be visited 20 times a year\n      No visits in December or January\n      Hedges to be cut twice a year\n      Regular grass cuts and weed control\n      Extra jobs to be billed in addition to standard payments"
  }])


export const CustomersContext = React.createContext()
export const useCustomers = ()=>{
  return useContext(CustomersContext)
}

export const CustomersProvider = ({children})=>{
  const [customerList,setCustomerList]=useState(JSON.parse(customerData))
  const [updateTrigger, setUpdateTrigger]=useState(false)

  useEffect(()=>{
    console.log(updateTrigger);
  },[updateTrigger])
  
  return (
    <CustomersContext.Provider value={[customerList,setCustomerList,setUpdateTrigger]}>
      {children}
    </CustomersContext.Provider>
  )
}
